# Generated by Django 4.2.7 on 2025-06-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='exercices/')),
                ('type_exercice', models.CharField(choices=[('situation_probleme', 'Situation Problème'), ('partie_a', 'Partie A'), ('partie_b', 'Partie B'), ('partie_c', 'Partie C'), ('traditionnelle', 'Exercice Traditionnel')], max_length=30)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.classe')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.lecon')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.theme')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.trimestre')),
            ],
        ),
    ]
