# Generated by Django 4.2.7 on 2025-06-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedagogie.trimestre'),
            preserve_default=False,
        ),
    ]
