# Generated by Django 4.2.7 on 2025-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_lecon_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='fichier_pdf',
        ),
        migrations.AddField(
            model_name='exercice',
            name='fichier_tex',
            field=models.FileField(default=1, upload_to='exercices_tex/'),
            preserve_default=False,
        ),
    ]
