# Generated by Django 4.2.7 on 2025-06-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
