# Generated by Django 4.2.7 on 2025-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_professeur_is_admin_demandeabonnement_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
